-- NOVE DRZAVE

INSERT INTO KS55324_DRZAVA (DRZAVA_ID, NAZIV)
SELECT 5 + ROW_NUMBER() OVER (ORDER BY country) AS DRZAVA_ID,
       country
FROM (
  SELECT DISTINCT TRIM(country) AS country
  FROM KS55324_STG_WORLDCITIES
  WHERE country IS NOT NULL
    AND TRIM(country) NOT IN (
      'Srbija',
      'Crna Gora',
      'Bosna',
      'Hrvatska',
      'Afghanistan'
    )
);

COMMIT;

SELECT COUNT(*) FROM KS55324_DRZAVA;
--NOVI GRADOVI

INSERT INTO KS55324_GRAD (GRAD_ID, NAZIV, POST_BROJ, REGION_ID)
SELECT 5 + ROW_NUMBER() OVER (ORDER BY s.city, r.REGION_ID) AS GRAD_ID,
       s.city,
       NULL AS POST_BROJ,
       r.REGION_ID
FROM (
  SELECT DISTINCT TRIM(city) AS city,
                  TRIM(country) AS country,
                  TRIM(admin_name) AS admin_name
  FROM KS55324_STG_WORLDCITIES
  WHERE city IS NOT NULL
    AND country IS NOT NULL
    AND admin_name IS NOT NULL
) s
JOIN KS55324_DRZAVA d
  ON TRIM(d.NAZIV) = s.country
JOIN KS55324_REGION r
  ON r.DRZAVA_ID = d.DRZAVA_ID
 AND TRIM(r.NAZIV) = s.admin_name
WHERE NOT EXISTS (
  SELECT 1
  FROM KS55324_GRAD g
  WHERE TRIM(g.NAZIV) = s.city
    AND g.REGION_ID = r.REGION_ID
);

COMMIT;

SELECT COUNT(*) FROM KS55324_GRAD;

SELECT p.POSLOVNICA_ID, p.NAZIV, p.GRAD_ID, g.NAZIV AS GRAD
FROM KS55324_POSLOVNICA p
LEFT JOIN KS55324_GRAD g ON g.GRAD_ID = p.GRAD_ID
ORDER BY p.POSLOVNICA_ID;

-- NOVI REGIONI
INSERT INTO KS55324_REGION (REGION_ID, NAZIV, DRZAVA_ID)
SELECT 5 + ROW_NUMBER() OVER (ORDER BY d.DRZAVA_ID, s.admin_name) AS REGION_ID,
       s.admin_name,
       d.DRZAVA_ID
FROM (
  SELECT DISTINCT TRIM(country) AS country,
                  TRIM(admin_name) AS admin_name
  FROM KS55324_STG_WORLDCITIES
  WHERE country IS NOT NULL
    AND admin_name IS NOT NULL
) s
JOIN KS55324_DRZAVA d
  ON TRIM(d.NAZIV) = s.country
WHERE NOT EXISTS (
  SELECT 1
  FROM KS55324_REGION r
  WHERE TRIM(r.NAZIV) = s.admin_name
    AND r.DRZAVA_ID = d.DRZAVA_ID
);

COMMIT;

SELECT COUNT(*) FROM KS55324_REGION;

SELECT * 
FROM KS55324_REGION
ORDER BY REGION_ID;

--PROVERA

SELECT COUNT(*) FROM KS55324_DRZAVA;
SELECT COUNT(*) FROM KS55324_REGION;
SELECT COUNT(*) FROM KS55324_GRAD;


SELECT p.POSLOVNICA_ID, p.NAZIV, p.GRAD_ID, g.NAZIV AS GRAD
FROM KS55324_POSLOVNICA p
LEFT JOIN KS55324_GRAD g ON g.GRAD_ID = p.GRAD_ID
ORDER BY p.POSLOVNICA_ID;

SELECT COUNT(DISTINCT TRIM(country))
FROM KS55324_STG_WORLDCITIES;

SELECT DISTINCT TRIM(country)
FROM KS55324_STG_WORLDCITIES
ORDER BY 1
FETCH FIRST 20 ROWS ONLY;

SELECT * 
FROM KS55324_DRZAVA
ORDER BY DRZAVA_ID;

INSERT INTO KS55324_DRZAVA (DRZAVA_ID, NAZIV)
VALUES (5, 'Afghanistan');

COMMIT;

SELECT * 
FROM KS55324_DRZAVA
ORDER BY DRZAVA_ID;