--------------------------------------------------------
--  File created - Tuesday-February-24-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table KS55324_FACT_OTPLATA
--------------------------------------------------------

  CREATE TABLE "SEDS"."KS55324_FACT_OTPLATA" 
   (	"OTPLATA_KEY" NUMBER, 
	"VREME_KEY" NUMBER, 
	"KLIJENT_KEY" NUMBER, 
	"TIP_KREDITA_KEY" NUMBER, 
	"POSLOVNICA_KEY" NUMBER, 
	"IZNOS_RATE" NUMBER(12,2), 
	"IZNOS_UPLACENO" NUMBER(12,2), 
	"DUG" NUMBER(12,2), 
	"KASNJENJE_DANA" NUMBER(6,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KS55324_DIM_VREME
--------------------------------------------------------

  CREATE TABLE "SEDS"."KS55324_DIM_VREME" 
   (	"VREME_KEY" NUMBER, 
	"DATUM" DATE, 
	"DAN" NUMBER(2,0), 
	"MESEC" NUMBER(2,0), 
	"NAZIV_MESECA" VARCHAR2(15 BYTE), 
	"KVARTAL" NUMBER(1,0), 
	"GODINA" NUMBER(4,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KS55324_DIM_KLIJENT
--------------------------------------------------------

  CREATE TABLE "SEDS"."KS55324_DIM_KLIJENT" 
   (	"KLIJENT_KEY" NUMBER, 
	"KLIJENT_ID" NUMBER, 
	"IME" VARCHAR2(80 BYTE), 
	"PREZIME" VARCHAR2(80 BYTE), 
	"POL" CHAR(1 BYTE), 
	"DATUM_RODJ" DATE, 
	"STAROSNA_GRUPA" VARCHAR2(20 BYTE), 
	"GRAD_KEY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KS55324_DIM_TIP_KREDITA
--------------------------------------------------------

  CREATE TABLE "SEDS"."KS55324_DIM_TIP_KREDITA" 
   (	"TIP_KREDITA_KEY" NUMBER, 
	"TIP_KREDITA_ID" NUMBER, 
	"NAZIV" VARCHAR2(120 BYTE), 
	"NOMINALNA_KAMATA" NUMBER(5,2), 
	"TIP" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KS55324_DIM_POSLOVNICA
--------------------------------------------------------

  CREATE TABLE "SEDS"."KS55324_DIM_POSLOVNICA" 
   (	"POSLOVNICA_KEY" NUMBER, 
	"POSLOVNICA_ID" NUMBER, 
	"NAZIV" VARCHAR2(150 BYTE), 
	"ADRESA" VARCHAR2(200 BYTE), 
	"GRAD_KEY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KS55324_DIM_GRAD
--------------------------------------------------------

  CREATE TABLE "SEDS"."KS55324_DIM_GRAD" 
   (	"GRAD_KEY" NUMBER, 
	"GRAD_ID" NUMBER, 
	"NAZIV" VARCHAR2(120 BYTE), 
	"POST_BROJ" VARCHAR2(20 BYTE), 
	"REGION_KEY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KS55324_DIM_DRZAVA
--------------------------------------------------------

  CREATE TABLE "SEDS"."KS55324_DIM_DRZAVA" 
   (	"DRZAVA_KEY" NUMBER, 
	"DRZAVA_ID" NUMBER, 
	"NAZIV" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table KS55324_DIM_REGION
--------------------------------------------------------

  CREATE TABLE "SEDS"."KS55324_DIM_REGION" 
   (	"REGION_KEY" NUMBER, 
	"REGION_ID" NUMBER, 
	"NAZIV" VARCHAR2(100 BYTE), 
	"DRZAVA_KEY" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0032759
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEDS"."SYS_C0032759" ON "SEDS"."KS55324_FACT_OTPLATA" ("OTPLATA_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0032750
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEDS"."SYS_C0032750" ON "SEDS"."KS55324_DIM_VREME" ("VREME_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0032742
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEDS"."SYS_C0032742" ON "SEDS"."KS55324_DIM_KLIJENT" ("KLIJENT_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0032734
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEDS"."SYS_C0032734" ON "SEDS"."KS55324_DIM_TIP_KREDITA" ("TIP_KREDITA_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0032728
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEDS"."SYS_C0032728" ON "SEDS"."KS55324_DIM_POSLOVNICA" ("POSLOVNICA_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0032722
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEDS"."SYS_C0032722" ON "SEDS"."KS55324_DIM_GRAD" ("GRAD_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0032713
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEDS"."SYS_C0032713" ON "SEDS"."KS55324_DIM_DRZAVA" ("DRZAVA_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C0032717
--------------------------------------------------------

  CREATE UNIQUE INDEX "SEDS"."SYS_C0032717" ON "SEDS"."KS55324_DIM_REGION" ("REGION_KEY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table KS55324_FACT_OTPLATA
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" MODIFY ("VREME_KEY" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" MODIFY ("KLIJENT_KEY" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" MODIFY ("TIP_KREDITA_KEY" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" MODIFY ("POSLOVNICA_KEY" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" MODIFY ("IZNOS_RATE" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" MODIFY ("IZNOS_UPLACENO" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" MODIFY ("DUG" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" MODIFY ("KASNJENJE_DANA" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" ADD PRIMARY KEY ("OTPLATA_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KS55324_DIM_VREME
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_VREME" MODIFY ("DATUM" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_VREME" MODIFY ("DAN" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_VREME" MODIFY ("MESEC" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_VREME" MODIFY ("NAZIV_MESECA" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_VREME" MODIFY ("KVARTAL" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_VREME" MODIFY ("GODINA" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_VREME" ADD PRIMARY KEY ("VREME_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KS55324_DIM_KLIJENT
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_KLIJENT" MODIFY ("KLIJENT_ID" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_KLIJENT" MODIFY ("IME" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_KLIJENT" MODIFY ("PREZIME" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_KLIJENT" MODIFY ("POL" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_KLIJENT" MODIFY ("DATUM_RODJ" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_KLIJENT" MODIFY ("STAROSNA_GRUPA" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_KLIJENT" MODIFY ("GRAD_KEY" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_KLIJENT" ADD PRIMARY KEY ("KLIJENT_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KS55324_DIM_TIP_KREDITA
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_TIP_KREDITA" MODIFY ("TIP_KREDITA_ID" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_TIP_KREDITA" MODIFY ("NAZIV" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_TIP_KREDITA" MODIFY ("NOMINALNA_KAMATA" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_TIP_KREDITA" MODIFY ("TIP" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_TIP_KREDITA" ADD PRIMARY KEY ("TIP_KREDITA_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KS55324_DIM_POSLOVNICA
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_POSLOVNICA" MODIFY ("POSLOVNICA_ID" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_POSLOVNICA" MODIFY ("NAZIV" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_POSLOVNICA" MODIFY ("ADRESA" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_POSLOVNICA" MODIFY ("GRAD_KEY" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_POSLOVNICA" ADD PRIMARY KEY ("POSLOVNICA_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KS55324_DIM_GRAD
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_GRAD" MODIFY ("GRAD_ID" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_GRAD" MODIFY ("NAZIV" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_GRAD" MODIFY ("REGION_KEY" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_GRAD" ADD PRIMARY KEY ("GRAD_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KS55324_DIM_DRZAVA
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_DRZAVA" MODIFY ("DRZAVA_ID" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_DRZAVA" MODIFY ("NAZIV" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_DRZAVA" ADD PRIMARY KEY ("DRZAVA_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KS55324_DIM_REGION
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_REGION" MODIFY ("REGION_ID" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_REGION" MODIFY ("NAZIV" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_REGION" MODIFY ("DRZAVA_KEY" NOT NULL ENABLE);
  ALTER TABLE "SEDS"."KS55324_DIM_REGION" ADD PRIMARY KEY ("REGION_KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KS55324_FACT_OTPLATA
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" ADD CONSTRAINT "KS55324_FK_FACT_VREME" FOREIGN KEY ("VREME_KEY")
	  REFERENCES "SEDS"."KS55324_DIM_VREME" ("VREME_KEY") ENABLE;
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" ADD CONSTRAINT "KS55324_FK_FACT_KLIJENT" FOREIGN KEY ("KLIJENT_KEY")
	  REFERENCES "SEDS"."KS55324_DIM_KLIJENT" ("KLIJENT_KEY") ENABLE;
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" ADD CONSTRAINT "KS55324_FK_FACT_TIP" FOREIGN KEY ("TIP_KREDITA_KEY")
	  REFERENCES "SEDS"."KS55324_DIM_TIP_KREDITA" ("TIP_KREDITA_KEY") ENABLE;
  ALTER TABLE "SEDS"."KS55324_FACT_OTPLATA" ADD CONSTRAINT "KS55324_FK_FACT_POSLOVNICA" FOREIGN KEY ("POSLOVNICA_KEY")
	  REFERENCES "SEDS"."KS55324_DIM_POSLOVNICA" ("POSLOVNICA_KEY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KS55324_DIM_KLIJENT
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_KLIJENT" ADD CONSTRAINT "KS55324_FK_DIM_KLIJENT_GRAD" FOREIGN KEY ("GRAD_KEY")
	  REFERENCES "SEDS"."KS55324_DIM_GRAD" ("GRAD_KEY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KS55324_DIM_POSLOVNICA
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_POSLOVNICA" ADD CONSTRAINT "KS55324_FK_DIM_POSLOVNICA_GRAD" FOREIGN KEY ("GRAD_KEY")
	  REFERENCES "SEDS"."KS55324_DIM_GRAD" ("GRAD_KEY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KS55324_DIM_GRAD
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_GRAD" ADD CONSTRAINT "KS55324_FK_DIM_GRAD_REGION" FOREIGN KEY ("REGION_KEY")
	  REFERENCES "SEDS"."KS55324_DIM_REGION" ("REGION_KEY") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KS55324_DIM_REGION
--------------------------------------------------------

  ALTER TABLE "SEDS"."KS55324_DIM_REGION" ADD CONSTRAINT "KS55324_FK_DIM_REGION_DRZAVA" FOREIGN KEY ("DRZAVA_KEY")
	  REFERENCES "SEDS"."KS55324_DIM_DRZAVA" ("DRZAVA_KEY") ENABLE;
