SELECT MVIEW_NAME
FROM USER_MVIEWS
WHERE MVIEW_NAME LIKE 'KS55324%';

--PRAVLJENJE MV-UPIT
--RACUNA UKUPNO PLACEN IZNIS, PROSECNO KASNJENJE, BROJ UPLATA

SELECT QUERY
FROM USER_MVIEWS
WHERE MVIEW_NAME = 'KS55324_MV_MESECNO_POSLOVNICA';

--AZURIRANJE PODATAKA, OSVEZAVA SE RUCNO, PO POTREBI

SELECT REFRESH_METHOD, REFRESH_MODE
FROM USER_MVIEWS
WHERE MVIEW_NAME = 'KS55324_MV_MESECNO_POSLOVNICA';

--POSLEDNJE AZURIRANJE

SELECT LAST_REFRESH_TYPE, LAST_REFRESH_DATE, STALENESS
FROM USER_MVIEWS
WHERE MVIEW_NAME = 'KS55324_MV_MESECNO_POSLOVNICA';

SELECT COUNT(*)
FROM KS55324_MV_MESECNO_POSLOVNICA;

SELECT *
FROM KS55324_MV_MESECNO_POSLOVNICA
FETCH FIRST 5 ROWS ONLY;

-- KAKO SAM NAPRAVILA - komanda

SELECT DBMS_METADATA.GET_DDL('MATERIALIZED_VIEW', 'KS55324_MV_MESECNO_POSLOVNICA')
FROM DUAL;

-- U seds.sql se nalazi