SELECT COUNT(*) FROM KS55324_FACT_OTPLATA;

SELECT COUNT(DISTINCT KLIJENT_ID) FROM KS55324_FACT_OTPLATA;

SELECT COUNT(*) FROM KS55324_DIM_DRZAVA;

SELECT COUNT(*) FROM KS55324_DIM_REGION;

SELECT COUNT(*) FROM KS55324_DIM_GRAD;

DELETE FROM KS55324_FACT_OTPLATA;
COMMIT;


--MAPRAVI DATUME
INSERT INTO KS55324_DIM_VREME (
    DATUM,
    DAN,
    MESEC,
    NAZIV_MESECA,
    KVARTAL,
    GODINA
)
SELECT
    d AS DATUM,
    EXTRACT(DAY FROM d) AS DAN,
    EXTRACT(MONTH FROM d) AS MESEC,
    TRIM(TO_CHAR(d, 'MONTH')) AS NAZIV_MESECA,
    TO_NUMBER(TO_CHAR(d, 'Q')) AS KVARTAL,
    EXTRACT(YEAR FROM d) AS GODINA
FROM (
    SELECT DATE '2010-01-01' + LEVEL - 1 AS d
    FROM dual
    CONNECT BY LEVEL <= (DATE '2030-12-31' - DATE '2010-01-01' + 1)
);

COMMIT;

--PROVERA

DELETE FROM KS55324_DIM_VREME;
COMMIT;

SELECT COUNT(*) FROM KS55324_DIM_VREME;


SELECT MIN(DATUM), MAX(DATUM)
FROM KS55324_DIM_VREME;


-- NAPUNI FACT

INSERT INTO KS55324_FACT_OTPLATA (
    OTPLATA_ID,
    DATUM,
    KLIJENT_ID,
    TIP_KREDITA_ID,
    POSLOVNICA_ID,
    IZNOS_RATE,
    IZNOS_UPLACENO,
    DUG,
    KASNJENJE_DANA
)
SELECT
    ROW_NUMBER() OVER (ORDER BY o.OTPLATA_ID) AS OTPLATA_ID,
    NVL(o.DATUM_UPLATE, o.DATUM_RATE) AS DATUM,
    dk.KLIJENT_ID AS KLIJENT_ID,
    dtk.TIP_KREDITA_ID AS TIP_KREDITA_ID,
    dp.POSLOVNICA_ID AS POSLOVNICA_ID,
    o.IZNOS_RATE,
    NVL(o.IZNOS_UPLACENO, 0) AS IZNOS_UPLACENO,
    (o.IZNOS_RATE - NVL(o.IZNOS_UPLACENO, 0)) AS DUG,
    NVL(o.KASNJENJE_DANA, 0) AS KASNJENJE_DANA
FROM KS55324_OTPLATA o
JOIN KS55324_KREDIT k ON k.KREDIT_ID = o.KREDIT_ID
LEFT JOIN KS55324_DIM_VREME dv ON dv.DATUM = NVL(o.DATUM_UPLATE, o.DATUM_RATE)
JOIN KS55324_DIM_KLIJENT dk ON dk.KLIJENT_ID = k.KLIJENT_ID
JOIN KS55324_DIM_TIP_KREDITA dtk ON dtk.TIP_KREDITA_ID = k.TIP_KREDITA_ID
JOIN KS55324_DIM_POSLOVNICA dp ON dp.POSLOVNICA_ID = k.POSLOVNICA_ID
WHERE NVL(o.DATUM_UPLATE, o.DATUM_RATE) IS NOT NULL;

COMMIT;